---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"

defaults:
  run:
    working-directory: 'nginx'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase nginx.
        uses: actions/checkout@v4
        with:
          path: 'nginx'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12' 

      - name: Install test dependencies.
        run: |
          pip install -r requirements.txt
          pip install ansible-core==2.16.8
          python -m site &> /dev/null && PATH="$PATH:`python -m site --user-base`/bin"
          molecule --version
          ansible --version
          pip freeze

      - name: Run Molecule tests.
        run: |
          molecule destroy --all
          molecule test
